package eu.kanade.tachiyomi.extension.pt.hentaihome

import eu.kanade.tachiyomi.source.model.Filter

class CategoryFilter :
    Filter.Select<String>(
        "Categoria",
        CATEGORIES.map { it.first }.toTypedArray(),
    ) {
    fun selected(): String = CATEGORIES[state].second

    companion object {
        private val CATEGORIES = arrayOf(
            Pair("Todas", ""),
            Pair("Aladdin", "disney-porno/aladdin/"),
            Pair("Animes", "animes/"),
            Pair("Attack On Titan Pornô", "attack-on-titan-porno/"),
            Pair("Ben 10 HQ Hentai", "ben-10-hq-hentai/"),
            Pair("Black Clover Hentai", "black-clover-hentai/"),
            Pair("Bleach", "bleach/"),
            Pair("Boku no Hero", "boku-no-hero/"),
            Pair("Boruto", "boruto/"),
            Pair("Cartoon Pornô", "cartoon-porno/"),
            Pair("Cartoon Pornô Gay", "cartoon-porno-gay/"),
            Pair("Cartoon de Incesto", "cartoon-de-incesto/"),
            Pair("Casa da Mãe Joana", "casa-da-mae-joana/"),
            Pair("Cavaleiros do Zodíaco Hentai", "cavaleiros-do-zodiaco-hentai/"),
            Pair("Chainsaw Man", "chainsaw-man/"),
            Pair("Chavitoon", "chavitoon/"),
            Pair("Contos de Sexo", "contos-de-sexo/"),
            Pair("Cosplay Hentai", "cosplay-hentai/"),
            Pair("DBZ Hentai", "dbz-hentai/"),
            Pair("Dandadan Hentai", "dandadan-hentai/"),
            Pair("Demon Slayer", "demon-slayer/"),
            Pair("Desenhos Pornô", "desenhos-porno/"),
            Pair("Disney Pornô", "disney-porno/"),
            Pair("Doujinshi", "doujinshi/"),
            Pair("Dr. Stone Pornô", "dr-stone-porno/"),
            Pair("Fairy Tail", "fairy-tail/"),
            Pair("Família Sacana", "familia-sacana/"),
            Pair("Fire Force Hentai", "fire-force-hentai/"),
            Pair("Futanari", "futanari/"),
            Pair("Genshin Impact", "genshin-impact/"),
            Pair("Goblin Slayer Hentai", "goblin-slayer-hentai/"),
            Pair("Gozando a vida adoidado", "gozando-a-vida-adoidado/"),
            Pair("Harry Potter", "harry-potter/"),
            Pair("Hentai Digimon", "hentai-digimon/"),
            Pair("Hentai Gay", "hentai-gay/"),
            Pair("Hentai Grátis", "hentai-gratis/"),
            Pair("Hentai One Piece", "hentai-one-piece/"),
            Pair("Heróis XXX", "herois-xxx/"),
            Pair("Homem-Aranha Pornô", "homem-aranha-porno/"),
            Pair("Incestos XXX", "incestos-xxx/"),
            Pair("Invencível Pornô", "invencivel-porno/"),
            Pair("Jujutsu Kaisen", "jujutsu-kaisen/"),
            Pair("Mangás", "mangas/"),
            Pair("Manhwa", "manhwa/"),
            Pair("Mansão Riqueza", "mansao-riqueza/"),
            Pair("Nanatsu no Taizai", "nanatsu-no-taizai/"),
            Pair("Naruto", "naruto/"),
            Pair("One Punch Man +18", "one-punch-man-18/"),
            Pair("One-Shot", "one-shot/"),
            Pair("Os Caipiras", "os-caipiras/"),
            Pair("Os Favelas", "os-favelas/"),
            Pair("Os Sacanas Filminho", "os-sacanas-filminho/"),
            Pair("Os Velhos da Praça", "os-velhos-da-praca/"),
            Pair("Papito o Sogro Tarado", "papito-o-sogro-tarado/"),
            Pair("Pokémon Hentai HQ", "pokemon-hentai-hq/"),
            Pair("Quadrinhos de Sexo", "quadrinhos-de-sexo/"),
            Pair("Ranma 1/2 Hentai", "ranma-1-2-hentai/"),
            Pair("Sailor Moon Pornô", "sailor-moon-porno/"),
            Pair("Scooby Doo Pornô", "scooby-doo-porno/"),
            Pair("Simptoons", "simptoons/"),
            Pair("Sousou no Frieren Hentai", "sousou-no-frieren-hentai/"),
            Pair("Spy × Family Hentai", "spy-x-family-hentai/"),
            Pair("Street Fighter Hentai HQ", "street-fighter-hentai-hq/"),
            Pair("Sucubbus", "sucubbus/"),
            Pair("Teen Titans", "teen-titans/"),
            Pair("The Flintstones Hentai", "the-flintstones-hentai/"),
            Pair("The Legend Of Zelda", "the-legend-of-zelda/"),
            Pair("The Simpsons", "the-simpsons/"),
            Pair("Tia, Primas e Cia", "tia-primas-e-cia/"),
            Pair("Videos Hentai", "videos-hentai/"),
            Pair("X-Men", "x-men/"),
            Pair("Yu Yu Hakusho Pornô", "yu-yu-hakusho-porno/"),
            Pair("Yu-Gi-Oh! Hentai", "yu-gi-oh-hentai/"),
            Pair("Zoo Hentai", "zoo-hentai/"),
        )
    }
}
